### ISSUE TITLE
Use of this library for huge xml processor

### ISSUE THREAD

**Issue by yellow1912** [borsodigerii/php-xml-chunker#1]
Instead of chunking the file, I wonder if this can act as a processor for a huge XML file. For example, given a file of 8GB XML, and with chunks of 100MB, perhaps we can calculate the number of chunks and loop through each chunk, or go directly to a specific chunk to process it reliable? Do you think it's possible?

**Comment by borsodigerii** [comment]
Hi there! If I understand your message correctly, you mean something like a callback, which is called every time a chunk is created with (let's say) the chunked data as parameter to that callback? So that a custom action can be bound on every chunk's completition. If yes, absolutely! If not, feel free to elaborate :)

**Comment by borsodigerii** [comment]
Closing this, I think you meant the custom callback, definetly on the To-Do's list!
